### ISSUE TITLE
Question: What do the 'n' and 'p' prefixes mean in RnaSynthProb output?

### ISSUE THREAD

**Issue by JosephCottam** [CovertLab/WholeCellEcoliRelease#11]
Some of the output columns have 'n' or 'p' prefixed.  From example, `RnaSynthProb` includes columns `nActualBound`, `pPromoterBound` and `nPromoterBound`.  What do these 'n' and 'p' prefixes mean?

**Comment by tahorst** [comment]
n = number
p = probability
