### ISSUE TITLE
RnaSynthProb is missing an attribute?

### ISSUE THREAD

**Issue by JosephCottam** [CovertLab/WholeCellEcoliRelease#12]
`RnaSynthProb` has three "columns" that are 22 columns wide: `nActualBound`, `pPromoterBound`, `nPromoterBound`.  However its only attribute is `rnaIds`, which has 4558 entries.  Most other tables there is an attribute of the appropriate shape to provide context to its columns (or the its trivial, like `time`).  It seems `RnaSynthProb` is missing an attribute.  What labels can I put on these 22 columns so I can interpret them?

**Comment by tahorst** [comment]
Sorry that the table is missing an attribute.  Each of those values corresponds to a specific transcription factor (`self.tfs` in the code below).  If you want the IDs, you would be able to pull them out of `sim_data` like in the following process file (which is where the listener data is written from):

https://github.com/CovertLab/WholeCellEcoliRelease/blob/457e914f63861fa963b4bd0e733c575753a6d1b8/models/ecoli/processes/tf_binding.py#L33-L34
