### ISSUE TITLE
Duplicate column names in doubling_times.tsv

### ISSUE THREAD

**Issue by john-s-f** [CovertLab/WholeCellEcoliRelease#18]
In your file at /reconstruction/ecoli/flat/rnaseq_data/doubling_times.tsv, you have duplicate column names where two columns are called M9 Glucose minus AAs (units.min), should one of these be plus AAs? The file rnaseq_rsem_tpm_mean.tsv does have a M9 Glucose plus AAs in it.

**Comment by ggsun** [comment]
Hi, @john-s-f, thanks for pointing this out.
This does seem like a typo, and the second `M9 Glucose minus AAs (units.min)` column should be corrected to `M9 Glucose plus AAs (units.min)`. At the current state, however, the file itself isn't used by the simulation so it shouldn't have any effect on the simulation itself. The file is likely to be removed in later releases if this continues to be the case.
