### ISSUE TITLE
Need github personal access token to pull docker image

### ISSUE THREAD

**Issue by djinnome** [CovertLab/WholeCellEcoliRelease#6]
Hi folks,

I tried to follow the directions to download the ecoli whole cell model from docker and ran into this problem:

```bash
bash-3.2$ docker pull docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full:latest
Error response from daemon: Get https://docker.pkg.github.com/v2/covertlab/wholecellecolirelease/wcm-full/manifests/latest: no basic auth credentials
```

The solution was to [create a personal access token](https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages) and execute this command first:

```bash
$ cat ~/TOKEN.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin
Login Succeeded
```

```bash
bash-3.2$ docker pull docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full:latest
latest: Pulling from covertlab/wholecellecolirelease/wcm-full

Digest: sha256:b1b945dbcec239de312eb02ed2709cc9e69afbf1dc3422571ca0c3a16b19ae9f
Status: Downloaded newer image for docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full:latest
docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full:latest

```

**Comment by kozo2** [comment]
The same for me.

```
~# docker pull docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full:latest
Error response from daemon: Get https://docker.pkg.github.com/v2/covertlab/wholecellecolirelease/wcm-full/manifests/latest: no basic auth credentials
```

**Comment by djinnome** [comment]
Hi folks,

I created these instructions for my forked repo. If you'd like, I can send you a pull request.

With Docker, you can start running a simulation with these steps:
1. Create a [github personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) with at least the `read:packages` permission selected.
1. Place the token in `github_personal_access_token.txt`.
1. Log in to `docker.pkg.github.com`:
    ```bash
    cat github_personal_access_token.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin
    ```
    You should see an output message like `Login Succeeded`
1.  Pull the Docker image:
    ```shell script
    docker pull docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full:latest
    ```
1. Run the Docker container:
    ```shell script
    docker run --name=wcm -it --rm docker.pkg.github.com/covertlab/wholecellecolirelease/wcm-full
    ```
1. Inside the container, run the model:
    ```shell script
    python runscripts/manual/runSim.py
    ```
