### ISSUE TITLE
Attempt to simulate minimal no glucose nutrient time series variant fails

### ISSUE THREAD

**Issue by djinnome** [CovertLab/WholeCellEcoliRelease#8]
Hi folks,

I tried to simulate 3 different nutrient time series variants, 

```python
python runscripts/manual/runSim.py --variant nutrientTimeSeries 0 2 /output
```

but ran into the following `KeyError` for `minimal_no_glucose` after it successfully ran at least one of the variants:

```python
Traceback (most recent call last):
  File "runscripts/manual/runSim.py", line 255, in <module>
    script.cli()
  File "/wcEcoli/wholecell/utils/scriptBase.py", line 276, in cli
    self.run(args)
  File "runscripts/manual/runSim.py", line 251, in run
    task.run_task({})
  File "/wcEcoli/wholecell/fireworks/firetasks/simulation.py", line 55, in run_task
    sim.run()
  File "/wcEcoli/wholecell/sim/simulation.py", line 205, in run
    self.run_incremental(self._lengthSec + self.initialTime())
  File "/wcEcoli/wholecell/sim/simulation.py", line 226, in run_incremental
    self._evolveState()
  File "/wcEcoli/wholecell/sim/simulation.py", line 323, in _evolveState
    listener.update()
  File "/wcEcoli/models/ecoli/listeners/cell_division.py", line 108, in update
    if self.dryMass - self.dryMassInitial >= self.expectedDryMassIncreaseDict[current_nutrients].asNumber(units.fg) * self.divisionMassMultiplier:
KeyError: 'minimal_no_glucose'
```

Let me know if there is something silly I am doing, or if this is a bug I have exposed

**Comment by tahorst** [comment]
The `nutrientTimeSeries` variant is not fully tested for all the time series and there's a note in the file that mentions there might be issues for anything besides the `minimal` media condition:
https://github.com/CovertLab/WholeCellEcoliRelease/blob/7e4cc9e57de76752df0f4e32eca95fb653ea64e4/models/ecoli/sim/variants/nutrientTimeSeries.py#L3

Sorry this message was not more obvious.  This is just a limitation of the extent of the current implementation and not a true bug or anything you were doing incorrectly.

**Comment by djinnome** [comment]
Hi @tahorst Thanks for the quick reply.  I think the problem was that I used the right indices, but the wrong variant.

I think I meant to run the [condition variant](https://github.com/CovertLab/WholeCellEcoliRelease/blob/7e4cc9e57de76752df0f4e32eca95fb653ea64e4/models/ecoli/sim/variants/condition.py) instead:

```
Expected variant indices (dependent on sorted order of sim_data.conditionActiveTfs):
	0: control
	1: anaerobic
	2: with amino acids
```

```bash
python runscripts/manual/runSim.py --variant condition 0 2 /output
```
