### ISSUE TITLE
Missing Table Metadata

### ISSUE THREAD

**Issue by JosephCottam** [CovertLab/WholeCellEcoliRelease#9]
It seems that `RnaDegradationListener` & `TranscriptElongationListener` are not saving geneIDs with their output, even though those IDs would be useful for interpreting results. 

For example --
```
tb = TableReader("WCOutputs/wildtype_000000/000000/generation_000000/000000/simOut/RnaDegradationListener")
print("Table shape:", tb.readColumn("countRnaDegraded").shape)

print("Attributes:")
for att in tb.attributeNames:
    print(tb.readAttribute(att))

Table Shape: (677, 4558)
Attributes:
counts
counts
counts
counts
counts
counts
```

In (most) other tables, there is an attribute with the right number of entries for the second dimension of the data.  In this case, the attributes are all just `counts`.  4558 is that same as the number of gene IDs used elsewhere (e.g., in `rnaSynthProb` the `rnaIDs` attribute).   

Can the ids be added to the output of `RnaDegradationListener` as well?

**Comment by tahorst** [comment]
As mentioned in the repo's README, this repo is a snapshot release that we will not be actively developing.  These attributes have already been added in our development repo so they will be available in our next release.  For now, you could use the `rnaIDs` from another listener as these should correspond to all RNA data of that length.
